version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  mongo:
    image: "mongo"
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor