version: "3.8"
services:
  web:
    build: .
    ports:
      - "1337:5000"
  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor